receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlphttp:
    logs_endpoint: http://host.docker.internal:8000/api/logs
    headers:
      Content-Type: application/x-protobuf
    tls:
      insecure: true

  debug:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
